"""Python track: concepts in prerequisite order, then activities.

Authoring rules (enforced by tests/test_content.py):
  * every `predict` answer is produced by actually running `code`
  * every `fix`/`write`/`build` reference `solution` passes its own tests
  * every `fix` starter must FAIL its tests (otherwise there is no bug)
  * hints go conceptual -> partial example; the worked solution is level 3
Explanations are written for someone who has never programmed: short
sentences, one idea each, and the *why* stated out loud.
"""

TITLE = "Python from zero"

CONCEPTS = [
    {
        "id": "print",
        "title": "Printing text",
        "prereqs": [],
        "summary": "print() puts text on the screen. Text goes in quotes. Commas add spaces.",
        "project": "A program that prints a receipt-style layout.",
    },
    {
        "id": "variables",
        "title": "Variables and input",
        "prereqs": ["print"],
        "summary": "A variable is a name for a value. input() asks the person at the keyboard for text.",
        "project": "A greeter that asks your name and answers back.",
    },
    {
        "id": "numbers",
        "title": "Numbers and arithmetic",
        "prereqs": ["variables"],
        "summary": "Whole numbers (int) and decimals (float). // divides and drops the remainder; % gives the remainder.",
        "project": "A tip calculator and a change-maker.",
    },
    {
        "id": "conditionals",
        "title": "Making decisions",
        "prereqs": ["numbers"],
        "summary": "if / elif / else runs different code depending on a yes-or-no question.",
        "project": "A tiny text game that reacts to what you type.",
    },
    {
        "id": "for_loops",
        "title": "Repeating with for",
        "prereqs": ["conditionals"],
        "summary": "A for loop runs the same block once for each item. range(n) counts 0 up to n-1.",
        "project": "A batch renamer that makes 10 file names in one go.",
    },
    {
        "id": "lists",
        "title": "Lists",
        "prereqs": ["for_loops"],
        "summary": "A list holds many values in order. Positions start at 0. append adds to the end.",
        "project": "A shopping list with a running total.",
    },
    {
        "id": "while_loops",
        "title": "Repeating until",
        "prereqs": ["conditionals"],
        "summary": "A while loop keeps going as long as a condition stays true.",
        "project": "A guess-the-number game that keeps asking until you win.",
    },
    {
        "id": "functions",
        "title": "Functions",
        "prereqs": ["for_loops"],
        "summary": "def packages steps under a name so you can reuse them. return hands a result back.",
        "project": "A small toolkit of reusable helpers.",
    },
    {
        "id": "strings",
        "title": "String tricks",
        "prereqs": ["lists"],
        "summary": "Strings can be sliced, upper-cased, split into words and counted.",
        "project": "A word counter and an initials maker.",
    },
    {
        "id": "dicts",
        "title": "Dictionaries",
        "prereqs": ["lists", "functions"],
        "summary": "A dictionary maps a key to a value, like a word to its definition.",
        "project": "A phone book and a word-frequency counter.",
    },
]

ACTIVITIES = [
    # ------------------------------------------------------------------ print
    {
        "id": "print.hook", "concept": "print", "kind": "predict", "role": "hook",
        "title": "What does the computer say?", "difficulty": 1, "minutes": 2,
        "hook": "Three lines of code. One of them looks like maths. What appears on screen?",
        "prompt": "Type exactly what this program prints, line by line.",
        "code": 'print("2 + 2")\nprint(2 + 2)\nprint("2 + 2 =", 2 + 2)',
        "answer": "2 + 2\n4\n2 + 2 = 4",
        "hints": [
            "Quotes mean 'this is text, show it as-is'. No quotes means 'work it out'.",
            "Line 1 prints the characters 2 + 2. Line 2 does the sum first. Line 3 prints both, with a space where the comma is.",
        ],
        "explain": "print() shows whatever you give it. Text in quotes is shown exactly as written — Python does not look inside it. Without quotes, Python calculates first and prints the result. A comma between two things prints both, with one space between them.",
        "explain_alt": "Think of quotes as a label on a box: whatever is written on the label is shown as-is. Without the label, Python opens the box and shows what's really inside (the answer 4).",
        "why": "This is the first rule of Python: quotes make text, no quotes makes a value. Almost every confusing beginner error comes from mixing those up.",
        "can_now": "You can tell the difference between text and a calculation, and print both on one line.",
    },
    {
        "id": "print.explain", "concept": "print", "kind": "explain", "role": "apply",
        "title": "Say it in your words", "difficulty": 1, "minutes": 1,
        "hook": "Explaining forces the idea to settle. One or two sentences is enough.",
        "prompt": "Why does print(\"2 + 2\") show the characters 2 + 2, but print(2 + 2) shows 4?",
        "model_answer": "Quotes turn something into text, and Python shows text exactly as written. Without quotes, 2 + 2 is an arithmetic expression, so Python calculates it and prints the result, 4.",
        "checklist": ["Mentioned that quotes make it text", "Mentioned that Python calculates the unquoted version"],
        "explain": "Compare your explanation to the model answer. You do not need the same words — only the same two ideas.",
        "can_now": "You explained why quotes matter.",
    },
    {
        "id": "print.fix", "concept": "print", "kind": "fix", "role": "apply",
        "title": "Fix the greeting", "difficulty": 1, "minutes": 2,
        "hook": "This program is supposed to print: Hello, world!  — but it crashes. Can you spot the missing character?",
        "prompt": "Fix the one mistake so the program prints exactly: Hello, world!",
        "code": 'print("Hello, world!)',
        "solution": 'print("Hello, world!")',
        "io_tests": [{"stdin": "", "expect": "Hello, world!"}],
        "hints": [
            "Every opening quote needs a closing quote.",
            "Count the quote marks. There is one. There should be two: print(\"...\")",
        ],
        "explain": "Python read the opening quote and kept reading, waiting for the closing one that never came. That is the error message 'unterminated string'. The fix is the missing quote.",
        "why": "Errors are usually Python telling you exactly where it got confused. Reading the last line of an error is a real skill — you just used it.",
        "can_now": "You fixed a quote error, which is the most common beginner crash.",
    },
    {
        "id": "print.build", "concept": "print", "kind": "build", "role": "build",
        "title": "Build: a tiny receipt", "difficulty": 1, "minutes": 3,
        "hook": "Shops print receipts with lines and totals. You can too, with three print calls.",
        "prompt": "Write a program that prints exactly these three lines:\n\nCoffee  3.50\n--------\nTotal   3.50\n\n(Two spaces after Coffee, three after Total. The middle line is eight dashes.)",
        "code": "# your code here\n",
        "solution": 'print("Coffee  3.50")\nprint("--------")\nprint("Total   3.50")',
        "io_tests": [{"stdin": "", "expect": "Coffee  3.50\n--------\nTotal   3.50"}],
        "hints": [
            "One print() per line. Everything, including spaces, goes inside the quotes.",
            "print(\"Coffee  3.50\") is the first line. Two more like it.",
        ],
        "explain": "Each print() ends by moving to a new line. Spaces inside quotes are kept exactly. That is all a receipt is: text lined up on purpose.",
        "why": "Formatting output is a real job. Every report and log starts as text placed exactly where you want it.",
        "can_now": "You built a program that lays text out on purpose.",
    },
    {
        "id": "print.review1", "concept": "print", "kind": "predict", "role": "review",
        "title": "Quotes or not?", "difficulty": 1, "minutes": 1,
        "hook": "Same idea, new numbers.",
        "prompt": "What does this print?",
        "code": 'print("10 - 3")\nprint(10 - 3)',
        "answer": "10 - 3\n7",
        "hints": ["Quotes: shown as written. No quotes: calculated.", "Line 1 is text. Line 2 is 7."],
        "explain": "Quotes make text; no quotes makes Python calculate.",
        "can_now": "You still know the quotes rule without help.",
    },
    {
        "id": "print.review2", "concept": "print", "kind": "predict", "role": "review",
        "title": "Commas add spaces", "difficulty": 1, "minutes": 1,
        "hook": "Where do the spaces come from?",
        "prompt": "What does this print? (Watch the spacing.)",
        "code": 'print("a", "b")\nprint("a" + "b")',
        "answer": "a b\nab",
        "hints": ["A comma in print adds a space. A + joins text with nothing between.", "First line: a space b. Second: ab."],
        "explain": "print(x, y) separates with a space. \"a\" + \"b\" glues the two texts together with nothing in between.",
        "can_now": "You can control whether output has spaces.",
    },

    # -------------------------------------------------------------- variables
    {
        "id": "variables.hook", "concept": "variables", "kind": "predict", "role": "hook",
        "title": "A name that changes", "difficulty": 1, "minutes": 2,
        "hook": "The same name, score, is printed twice — and prints two different things. Why?",
        "prompt": "What does this print?",
        "code": "score = 10\nprint(score)\nscore = score + 5\nprint(score)",
        "answer": "10\n15",
        "hints": [
            "= does not mean 'equals'. It means 'store this value under this name'.",
            "score = score + 5 reads the old value (10), adds 5, and stores 15 under the same name.",
        ],
        "explain": "A variable is a labelled box. score = 10 puts 10 in a box labelled score. Reading score gives you what's in the box. score = score + 5 works right-to-left: first work out score + 5 (15), then store it back in the box.",
        "explain_alt": "Think of a whiteboard with 'score: 10' written on it. The line score = score + 5 means: look at the board, add 5, wipe it, write the new number.",
        "why": "Programs are mostly about values that change over time — a total, a count, a position. Variables are how you keep track of them.",
        "can_now": "You can read a program where a value changes and predict its output.",
    },
    {
        "id": "variables.explain", "concept": "variables", "kind": "explain", "role": "apply",
        "title": "What does = really do?", "difficulty": 1, "minutes": 1,
        "hook": "This one trips up a lot of people, so it is worth saying out loud.",
        "prompt": "In your own words: what happens when Python runs  x = x + 1  ?",
        "model_answer": "Python first works out the right-hand side using the current value of x, then stores that result back into x. So x ends up one bigger than before.",
        "checklist": ["Said the right side is calculated first", "Said the result is stored back into the same name"],
        "explain": "The key idea is order: right side first, then store. That is why a line that would be nonsense in maths (x = x + 1) is completely normal in code.",
        "can_now": "You explained assignment, the most-used line in all of programming.",
    },
    {
        "id": "variables.write", "concept": "variables", "kind": "write", "role": "apply",
        "title": "Ask, then answer", "difficulty": 1, "minutes": 3,
        "hook": "Programs that talk back feel alive. This one takes two lines.",
        "prompt": "Write a program that asks for a name with input() and then prints:  Hello, NAME!\n\nFor example, if the person types Ana, it prints:  Hello, Ana!",
        "code": "name = input()\n# print the greeting\n",
        "solution": 'name = input()\nprint("Hello, " + name + "!")',
        "io_tests": [
            {"stdin": "Ana\n", "expect": "Hello, Ana!"},
            {"stdin": "Tommy\n", "expect": "Hello, Tommy!"},
        ],
        "hints": [
            "input() waits for the person to type, then gives you their text. Store it in a variable.",
            "Join text with +:  \"Hello, \" + name + \"!\"   Or use a comma — but a comma adds a space before the !",
        ],
        "explain": "input() pauses and returns what was typed, as text. Storing it in name lets you use it later. \"Hello, \" + name + \"!\" glues three pieces of text together.",
        "why": "Every interactive program follows this shape: get some input, keep it in a variable, do something with it.",
        "can_now": "You wrote a program that responds to what a person types.",
    },
    {
        "id": "variables.build", "concept": "variables", "kind": "build", "role": "build",
        "title": "Build: a two-question greeter", "difficulty": 2, "minutes": 4,
        "hook": "Ask two things, combine them into one sentence.",
        "prompt": "Ask for a name (first input) then a city (second input). Print:\n\nNAME lives in CITY.\n\nExample: inputs Ana then Lisbon → prints  Ana lives in Lisbon.",
        "code": "name = input()\ncity = input()\n",
        "solution": 'name = input()\ncity = input()\nprint(name + " lives in " + city + ".")',
        "io_tests": [
            {"stdin": "Ana\nLisbon\n", "expect": "Ana lives in Lisbon."},
            {"stdin": "Kai\nManila\n", "expect": "Kai lives in Manila."},
        ],
        "hints": [
            "Two input() calls, two variables. Then one print that joins them.",
            "print(name + \" lives in \" + city + \".\")",
        ],
        "explain": "Each input() gives you the next line the person typed. Variables keep them apart. Building a sentence is just gluing text pieces in order.",
        "why": "Combining stored values into a message is the core of everything from chat apps to invoices.",
        "can_now": "You built a program that collects two facts and combines them.",
    },
    {
        "id": "variables.review1", "concept": "variables", "kind": "predict", "role": "review",
        "title": "Swap trace", "difficulty": 2, "minutes": 2,
        "hook": "Two boxes, values moving between them.",
        "prompt": "What does this print?",
        "code": "a = 1\nb = 2\na = b\nb = 5\nprint(a, b)",
        "answer": "2 5",
        "hints": ["a = b copies b's current value into a. It does not link them.", "After a = b, a is 2. Changing b later does not change a."],
        "explain": "Assignment copies the value at that moment. a = b makes a hold 2. Then b becomes 5, but a stays 2.",
        "can_now": "You can trace variables through several assignments.",
    },
    {
        "id": "variables.review2", "concept": "variables", "kind": "write", "role": "review",
        "title": "Echo twice", "difficulty": 1, "minutes": 2,
        "hook": "A small variation on the greeter.",
        "prompt": "Read one line with input() and print it twice, on two lines.",
        "code": "",
        "solution": "word = input()\nprint(word)\nprint(word)",
        "io_tests": [{"stdin": "echo\n", "expect": "echo\necho"}],
        "hints": ["Store the input in a variable, then print that variable twice.", "word = input() then two print(word) lines."],
        "explain": "Once a value is in a variable you can use it as many times as you like.",
        "can_now": "You reused a stored value.",
    },

    # ---------------------------------------------------------------- numbers
    {
        "id": "numbers.hook", "concept": "numbers", "kind": "predict", "role": "hook",
        "title": "Two kinds of divide", "difficulty": 1, "minutes": 2,
        "hook": "7 divided by 2 is 3.5. But Python has a second divide that answers 3, and a third symbol that answers 1. Useful for making change and splitting things into groups.",
        "prompt": "What does this print?",
        "code": "print(7 / 2)\nprint(7 // 2)\nprint(7 % 2)",
        "answer": "3.5\n3\n1",
        "hints": [
            "/ is normal division. // throws away the remainder. % gives only the remainder.",
            "7 / 2 = 3.5. 7 // 2 = 3 (whole part). 7 % 2 = 1 (what's left over).",
        ],
        "explain": "/ always gives a decimal (a float), even 6 / 2 gives 3.0. // is 'how many whole times does it fit' — 7 // 2 is 3. % is 'what is left over' — 7 % 2 is 1. Together // and % answer 'how many groups, and how many left'.",
        "explain_alt": "Sharing 7 sweets between 2 kids: each gets 3 (that's //), and 1 is left in the bag (that's %). / is the unfair answer, 3.5 sweets each.",
        "why": "% is how programs check 'is this even?' (x % 2 == 0), 'is it a multiple of 5?', and how change-makers count coins.",
        "can_now": "You know three kinds of division and when each is useful.",
    },
    {
        "id": "numbers.explain", "concept": "numbers", "kind": "explain", "role": "apply",
        "title": "Why is 7 // 2 three?", "difficulty": 1, "minutes": 1,
        "hook": "Say it plainly.",
        "prompt": "Explain what // and % do, using 17 and 5 as your example.",
        "model_answer": "17 // 5 is 3 because 5 fits into 17 three whole times. 17 % 5 is 2 because after taking out three 5s (15), 2 is left over.",
        "checklist": ["Said // gives the whole number of times it fits", "Said % gives what is left over"],
        "explain": "If you got both ideas, you understand integer division.",
        "can_now": "You explained integer division and remainder.",
    },
    {
        "id": "numbers.fix", "concept": "numbers", "kind": "fix", "role": "apply",
        "title": "Fix the tip calculator", "difficulty": 2, "minutes": 3,
        "hook": "This tip calculator crashes with: TypeError: can't multiply sequence by non-int of type 'float'. One conversion fixes it.",
        "prompt": "Make the function work. It should take a bill as text (like \"40\") and return the tip (15%) as a number. tip(\"40\") should return 6.0",
        "code": 'def tip(bill_text):\n    bill = bill_text\n    return bill * 0.15\n',
        "solution": 'def tip(bill_text):\n    bill = float(bill_text)\n    return bill * 0.15\n',
        "tests": [
            {"fn": "tip", "args": ["40"], "expect": 6.0},
            {"fn": "tip", "args": ["100"], "expect": 15.0},
        ],
        "hints": [
            "input() and other text sources give you text, even when it looks like a number. \"40\" * 0.15 makes no sense to Python.",
            "Convert first: float(bill_text) turns \"40\" into 40.0. Then multiply.",
        ],
        "explain": "\"40\" (text) and 40 (a number) are different things to Python. Maths only works on numbers. float(\"40\") converts text to a decimal number; int(\"40\") converts to a whole number.",
        "why": "Almost everything that comes from a keyboard, file or web page arrives as text. Converting it is step one of every calculation.",
        "can_now": "You fixed a type error by converting text to a number.",
    },
    {
        "id": "numbers.build", "concept": "numbers", "kind": "build", "role": "build",
        "title": "Build: make change", "difficulty": 2, "minutes": 4,
        "hook": "Given 67 cents, a cashier hands over 2 quarters and 17 cents. // and % can do this.",
        "prompt": "Write a function change(cents) that returns how many quarters (25) and how many cents remain, as a pair. change(67) should return (2, 17).",
        "code": "def change(cents):\n    # quarters = ...\n    # left = ...\n    return (0, 0)\n",
        "solution": "def change(cents):\n    quarters = cents // 25\n    left = cents % 25\n    return (quarters, left)\n",
        "tests": [
            {"fn": "change", "args": [67], "expect": (2, 17)},
            {"fn": "change", "args": [100], "expect": (4, 0)},
            {"fn": "change", "args": [24], "expect": (0, 24)},
        ],
        "hints": [
            "How many whole quarters fit in 67? That's //. What's left after them? That's %.",
            "quarters = cents // 25 and left = cents % 25. Return them as (quarters, left).",
        ],
        "explain": "cents // 25 counts whole quarters. cents % 25 is the leftover. Returning (a, b) gives back two values at once — a 'tuple', which is just a fixed pair.",
        "why": "This exact pattern converts seconds to minutes, cents to coins, and items to boxes. Once you see it you'll spot it everywhere.",
        "can_now": "You built a change-maker with integer division and remainder.",
    },
    {
        "id": "numbers.review1", "concept": "numbers", "kind": "predict", "role": "review",
        "title": "Minutes and seconds", "difficulty": 2, "minutes": 2,
        "hook": "Same trick, different units.",
        "prompt": "What does this print?",
        "code": "total = 130\nprint(total // 60, total % 60)",
        "answer": "2 10",
        "hints": ["130 seconds is how many whole minutes, and how many seconds left?", "130 // 60 = 2, 130 % 60 = 10."],
        "explain": "// gives the whole minutes, % gives the seconds that didn't fill a minute.",
        "can_now": "You can convert units with // and %.",
    },
    {
        "id": "numbers.review2", "concept": "numbers", "kind": "predict", "role": "review",
        "title": "Text plus text", "difficulty": 2, "minutes": 1,
        "hook": "Looks like maths. Isn't.",
        "prompt": "What does this print?",
        "code": 'a = "3"\nb = "4"\nprint(a + b)\nprint(int(a) + int(b))',
        "answer": "34\n7",
        "hints": ["\"3\" and \"4\" are text. + on text glues.", "Line 1 glues into 34. Line 2 converts to numbers first, giving 7."],
        "explain": "Text + text joins them. int() converts text to a number so + adds.",
        "can_now": "You can tell text arithmetic from number arithmetic.",
    },

    # ----------------------------------------------------------- conditionals
    {
        "id": "conditionals.hook", "concept": "conditionals", "kind": "predict", "role": "hook",
        "title": "A door that only opens sometimes", "difficulty": 1, "minutes": 2,
        "hook": "This is the start of every game: the program does something different depending on a value.",
        "prompt": "What does this print?",
        "code": 'age = 15\nif age >= 18:\n    print("Welcome in.")\nelse:\n    print("Sorry, not yet.")\nprint("Bye!")',
        "answer": "Sorry, not yet.\nBye!",
        "hints": [
            "if asks a yes/no question. The indented block under it runs only when the answer is yes.",
            "15 >= 18 is False, so the else block runs. The last print is not indented, so it always runs.",
        ],
        "explain": "if CONDITION: runs the indented lines only when the condition is True. else: runs when it is False. Lines that are not indented are outside the decision and always run. The indentation is not decoration — it is how Python knows what belongs to the if.",
        "explain_alt": "Picture a fork in a path. The condition is the signpost. You walk one branch or the other, never both, and afterwards the paths join again (the unindented line).",
        "why": "Indentation defines structure in Python. Getting this right is the difference between a program that works and one that mysteriously prints too much.",
        "can_now": "You can read an if/else and say which branch runs.",
    },
    {
        "id": "conditionals.explain", "concept": "conditionals", "kind": "explain", "role": "apply",
        "title": "Why the indent matters", "difficulty": 1, "minutes": 1,
        "hook": "This is the idea beginners most often half-understand.",
        "prompt": "Why did  print(\"Bye!\")  run even though the if was false?",
        "model_answer": "Because it is not indented under the if or the else. Indentation tells Python which lines belong to a branch; an unindented line is outside the decision, so it always runs.",
        "checklist": ["Mentioned indentation", "Said the unindented line is outside the if/else"],
        "explain": "Indented = inside the decision. Not indented = after the decision.",
        "can_now": "You explained how indentation controls what runs.",
    },
    {
        "id": "conditionals.fix", "concept": "conditionals", "kind": "fix", "role": "apply",
        "title": "Fix the grade checker", "difficulty": 2, "minutes": 3,
        "hook": "grade(95) should say 'A' and grade(85) should say 'B'. Right now everything is an 'A'. One comparison is wrong.",
        "prompt": "Fix the function. 90 and above → \"A\", 80–89 → \"B\", below 80 → \"C\".",
        "code": 'def grade(score):\n    if score >= 80:\n        return "A"\n    elif score >= 80:\n        return "B"\n    else:\n        return "C"\n',
        "solution": 'def grade(score):\n    if score >= 90:\n        return "A"\n    elif score >= 80:\n        return "B"\n    else:\n        return "C"\n',
        "tests": [
            {"fn": "grade", "args": [95], "expect": "A"},
            {"fn": "grade", "args": [90], "expect": "A"},
            {"fn": "grade", "args": [85], "expect": "B"},
            {"fn": "grade", "args": [79], "expect": "C"},
        ],
        "hints": [
            "Python checks the conditions top to bottom and takes the first one that is true. Look at the first condition.",
            "The first check should be score >= 90. Then elif score >= 80 catches the B range.",
        ],
        "explain": "if / elif / else is checked in order. The first True branch wins and the rest are skipped. Because the first check was >= 80, an 85 matched it and got 'A'. Ordering the checks from strictest to loosest fixes it.",
        "why": "Order of checks is a classic source of bugs. The fix is always: put the most specific condition first.",
        "can_now": "You fixed an ordering bug in an if/elif chain.",
    },
    {
        "id": "conditionals.build", "concept": "conditionals", "kind": "build", "role": "build",
        "title": "Build: the cave game", "difficulty": 2, "minutes": 5,
        "hook": "A text adventure in 8 lines. Change the if and the game changes.",
        "prompt": "You are in a cave. Read one line of input. If it is \"left\" print \"You find treasure!\". If it is \"right\" print \"A dragon! Run!\". Anything else: print \"You bump into a wall.\"",
        "code": "choice = input()\n# if / elif / else\n",
        "solution": 'choice = input()\nif choice == "left":\n    print("You find treasure!")\nelif choice == "right":\n    print("A dragon! Run!")\nelse:\n    print("You bump into a wall.")',
        "io_tests": [
            {"stdin": "left\n", "expect": "You find treasure!"},
            {"stdin": "right\n", "expect": "A dragon! Run!"},
            {"stdin": "up\n", "expect": "You bump into a wall."},
        ],
        "hints": [
            "Compare text with ==. Two branches for the two directions, else for everything else.",
            "if choice == \"left\": ... elif choice == \"right\": ... else: ...",
        ],
        "explain": "== asks 'are these equal?' and gives True or False. That answer drives the if. Three outcomes need if, elif, else.",
        "why": "This is the skeleton of every menu, every command parser and every game. Add more elifs and you have a bigger world.",
        "can_now": "You built a program that reacts differently to different input.",
    },
    {
        "id": "conditionals.review1", "concept": "conditionals", "kind": "predict", "role": "review",
        "title": "Which branch?", "difficulty": 2, "minutes": 2,
        "hook": "Trace it carefully; only one line prints.",
        "prompt": "What does this print?",
        "code": 'temp = 22\nif temp > 30:\n    print("hot")\nelif temp > 20:\n    print("warm")\nelif temp > 10:\n    print("mild")\nelse:\n    print("cold")',
        "answer": "warm",
        "hints": ["First True condition wins, top to bottom.", "22 > 30 is False. 22 > 20 is True → warm. The rest is skipped."],
        "explain": "Only the first matching branch runs, even if later ones would also be true.",
        "can_now": "You can trace an elif chain independently.",
    },
    {
        "id": "conditionals.review2", "concept": "conditionals", "kind": "write", "role": "review",
        "title": "Even or odd", "difficulty": 2, "minutes": 3,
        "hook": "Numbers plus decisions: the % trick from earlier.",
        "prompt": "Write a function parity(n) that returns \"even\" if n is even and \"odd\" otherwise.",
        "code": "def parity(n):\n    pass\n",
        "solution": 'def parity(n):\n    if n % 2 == 0:\n        return "even"\n    else:\n        return "odd"\n',
        "tests": [
            {"fn": "parity", "args": [4], "expect": "even"},
            {"fn": "parity", "args": [7], "expect": "odd"},
            {"fn": "parity", "args": [0], "expect": "even"},
        ],
        "hints": ["An even number has no remainder when divided by 2.", "if n % 2 == 0: return \"even\" else return \"odd\"."],
        "explain": "n % 2 is 0 for even numbers. Comparing with == 0 gives the True/False an if needs.",
        "can_now": "You combined remainder and a decision — two concepts at once.",
    },
    {
        "id": "conditionals.cumulative", "concept": "conditionals", "kind": "write", "role": "cumulative",
        "title": "Challenge: ticket price", "difficulty": 3, "minutes": 5,
        "hook": "Uses numbers and decisions together.",
        "prompt": "Write price(age) that returns 0 for age under 5, 8 for age 5–17, 12 for 18–64, and 9 for 65 and over.",
        "code": "def price(age):\n    pass\n",
        "solution": "def price(age):\n    if age < 5:\n        return 0\n    elif age <= 17:\n        return 8\n    elif age <= 64:\n        return 12\n    else:\n        return 9\n",
        "tests": [
            {"fn": "price", "args": [3], "expect": 0},
            {"fn": "price", "args": [5], "expect": 8},
            {"fn": "price", "args": [17], "expect": 8},
            {"fn": "price", "args": [30], "expect": 12},
            {"fn": "price", "args": [65], "expect": 9},
        ],
        "hints": ["Order the checks from youngest to oldest so each elif only needs an upper bound.", "if age < 5 → 0, elif age <= 17 → 8, elif age <= 64 → 12, else → 9."],
        "explain": "Because branches are checked in order, each one can assume the earlier ones failed. That is why elif age <= 17 doesn't need to also say 'and age >= 5'.",
        "can_now": "You wrote a four-way decision with clean, ordered conditions.",
    },

    # -------------------------------------------------------------- for_loops
    {
        "id": "for_loops.hook", "concept": "for_loops", "kind": "predict", "role": "hook",
        "title": "Two lines, five outputs", "difficulty": 1, "minutes": 2,
        "hook": "A loop is how a program does something 5 times — or 5 million — without you writing it out.",
        "prompt": "What does this print?",
        "code": 'for n in range(5):\n    print(n, "sheep")',
        "answer": "0 sheep\n1 sheep\n2 sheep\n3 sheep\n4 sheep",
        "hints": [
            "range(5) produces 0, 1, 2, 3, 4 — five numbers, starting at 0, stopping before 5.",
            "Each turn of the loop, n takes the next number and the print runs again.",
        ],
        "explain": "for n in range(5): runs the indented block five times. Each time, n holds the next number: 0, 1, 2, 3, 4. Counting starts at 0 and stops just before the number you give. It feels odd at first; it will feel natural soon, because list positions also start at 0.",
        "explain_alt": "range(5) is a dispenser with tickets 0–4. The loop takes one ticket at a time, runs the block, then comes back for the next until the dispenser is empty.",
        "why": "Loops are the single biggest reason to use a computer: repeat a boring thing perfectly, many times.",
        "can_now": "You can predict what a for loop over range prints, including the 0 start.",
    },
    {
        "id": "for_loops.explain", "concept": "for_loops", "kind": "explain", "role": "apply",
        "title": "Why a loop?", "difficulty": 1, "minutes": 1,
        "hook": "This is the sentence you will say in every code review.",
        "prompt": "Someone wrote print(1) print(2) ... print(100) on 100 lines. Explain why a loop is better and what range would you use?",
        "model_answer": "A loop writes the instruction once and repeats it, so it is shorter, easier to change and can't have a typo on line 73. for n in range(1, 101): print(n) — range(1, 101) starts at 1 and stops before 101.",
        "checklist": ["Gave a reason (shorter / easier to change / fewer mistakes)", "Used range with a start and an end that is one past the last number"],
        "explain": "range(start, stop) counts from start up to but not including stop.",
        "can_now": "You explained why this needs a loop.",
    },
    {
        "id": "for_loops.fix", "concept": "for_loops", "kind": "fix", "role": "apply",
        "title": "Fix the off-by-one", "difficulty": 2, "minutes": 3,
        "hook": "countdown(3) should return [3, 2, 1]. It returns [3, 2]. The classic off-by-one bug.",
        "prompt": "Fix it so countdown(n) returns the list n, n-1, ..., 1.",
        "code": "def countdown(n):\n    result = []\n    for i in range(n, 1, -1):\n        result.append(i)\n    return result\n",
        "solution": "def countdown(n):\n    result = []\n    for i in range(n, 0, -1):\n        result.append(i)\n    return result\n",
        "tests": [
            {"fn": "countdown", "args": [3], "expect": [3, 2, 1]},
            {"fn": "countdown", "args": [1], "expect": [1]},
            {"fn": "countdown", "args": [5], "expect": [5, 4, 3, 2, 1]},
        ],
        "hints": [
            "range(start, stop, step) stops BEFORE stop. What is the stop right now?",
            "To include 1, the stop must be 0: range(n, 0, -1).",
        ],
        "explain": "range(n, 1, -1) counts down from n and stops before reaching 1, so 1 is never included. Changing the stop to 0 includes 1. 'Stops before' is the rule to remember.",
        "why": "Off-by-one errors are the most common loop bug for everyone, not just beginners. Knowing to check the stop value fixes most of them.",
        "can_now": "You fixed an off-by-one error in a range.",
    },
    {
        "id": "for_loops.build", "concept": "for_loops", "kind": "build", "role": "build",
        "title": "Build: batch file names", "difficulty": 2, "minutes": 4,
        "hook": "Renaming 10 photos by hand is dull. A loop does it in one line.",
        "prompt": "Write names(count) that returns a list of file names photo_1.jpg, photo_2.jpg, ... up to photo_COUNT.jpg.",
        "code": "def names(count):\n    result = []\n    # loop and append\n    return result\n",
        "solution": 'def names(count):\n    result = []\n    for i in range(1, count + 1):\n        result.append("photo_" + str(i) + ".jpg")\n    return result\n',
        "tests": [
            {"fn": "names", "args": [3], "expect": ["photo_1.jpg", "photo_2.jpg", "photo_3.jpg"]},
            {"fn": "names", "args": [1], "expect": ["photo_1.jpg"]},
            {"fn": "names", "args": [0], "expect": []},
        ],
        "hints": [
            "You want 1 up to count, so range(1, count + 1). Numbers must become text before joining: str(i).",
            "result.append(\"photo_\" + str(i) + \".jpg\") inside the loop.",
        ],
        "explain": "range(1, count + 1) gives 1..count. str(i) turns the number into text so + can glue it into the name. append adds each name to the list.",
        "why": "This is a real batch operation: the same shape renames files, generates reports and creates user accounts.",
        "can_now": "You built a batch operation with a loop.",
    },
    {
        "id": "for_loops.review1", "concept": "for_loops", "kind": "predict", "role": "review",
        "title": "Running total", "difficulty": 2, "minutes": 2,
        "hook": "A loop plus a variable that accumulates.",
        "prompt": "What does this print?",
        "code": "total = 0\nfor n in range(1, 5):\n    total = total + n\nprint(total)",
        "answer": "10",
        "hints": ["range(1, 5) is 1, 2, 3, 4. Add them up.", "0+1=1, +2=3, +3=6, +4=10."],
        "explain": "The pattern 'start at 0, add each item' is called accumulating. It is how sums, counts and averages are computed.",
        "can_now": "You traced an accumulator loop.",
    },
    {
        "id": "for_loops.review2", "concept": "for_loops", "kind": "write", "role": "review",
        "title": "Stars", "difficulty": 2, "minutes": 3,
        "hook": "Loops can build text too.",
        "prompt": "Write stars(n) that returns a string of n asterisks. stars(3) returns \"***\".",
        "code": "def stars(n):\n    pass\n",
        "solution": 'def stars(n):\n    out = ""\n    for i in range(n):\n        out = out + "*"\n    return out\n',
        "tests": [
            {"fn": "stars", "args": [3], "expect": "***"},
            {"fn": "stars", "args": [0], "expect": ""},
        ],
        "hints": ["Start with an empty string and add one * each turn.", "out = \"\" then out = out + \"*\" inside for i in range(n)."],
        "explain": "Accumulating works on text exactly like on numbers: start empty, add a piece each time.",
        "can_now": "You built a string with a loop.",
    },
    {
        "id": "for_loops.cumulative", "concept": "for_loops", "kind": "write", "role": "cumulative",
        "title": "Challenge: FizzBuzz lite", "difficulty": 3, "minutes": 5,
        "hook": "Loops + decisions + remainder. A famous interview warm-up.",
        "prompt": "Write fizz(n) that returns a list for 1..n where multiples of 3 become \"Fizz\" and other numbers stay as numbers. fizz(6) → [1, 2, \"Fizz\", 4, 5, \"Fizz\"]",
        "code": "def fizz(n):\n    result = []\n    return result\n",
        "solution": 'def fizz(n):\n    result = []\n    for i in range(1, n + 1):\n        if i % 3 == 0:\n            result.append("Fizz")\n        else:\n            result.append(i)\n    return result\n',
        "tests": [
            {"fn": "fizz", "args": [6], "expect": [1, 2, "Fizz", 4, 5, "Fizz"]},
            {"fn": "fizz", "args": [2], "expect": [1, 2]},
        ],
        "hints": ["Loop 1..n. Inside, an if on i % 3.", "if i % 3 == 0: append \"Fizz\" else append i."],
        "explain": "A decision inside a loop is the most common shape in programming: for each thing, check something, act accordingly.",
        "can_now": "You combined a loop, a remainder check and a decision.",
    },

    # ------------------------------------------------------------------ lists
    {
        "id": "lists.hook", "concept": "lists", "kind": "predict", "role": "hook",
        "title": "Position zero", "difficulty": 1, "minutes": 2,
        "hook": "A list holds several things. Asking for the 'first' one is where everybody gets surprised once.",
        "prompt": "What does this print?",
        "code": 'colors = ["red", "green", "blue"]\nprint(colors[0])\nprint(colors[2])\nprint(len(colors))',
        "answer": "red\nblue\n3",
        "hints": [
            "Positions start at 0. colors[0] is the first item. len() counts items.",
            "[0] → red, [2] → blue (third item), len → 3.",
        ],
        "explain": "A list is an ordered row of values. You pick one with square brackets and a position; the first position is 0, so the last is len - 1. len(colors) tells you how many items there are.",
        "explain_alt": "Think of a street where house numbers start at 0. colors[2] is the third house along.",
        "why": "Starting at 0 matches how range works, which is why for i in range(len(colors)) walks every position.",
        "can_now": "You can read items out of a list by position.",
    },
    {
        "id": "lists.explain", "concept": "lists", "kind": "explain", "role": "apply",
        "title": "The index error", "difficulty": 1, "minutes": 1,
        "hook": "You will meet this error many times. Knowing why makes it a 10-second fix.",
        "prompt": "colors has 3 items. Why does colors[3] crash with IndexError, and what is the last valid position?",
        "model_answer": "Positions start at 0, so 3 items live at positions 0, 1, 2. Position 3 does not exist, so Python raises IndexError. The last valid position is len(colors) - 1, which is 2.",
        "checklist": ["Said positions start at 0", "Said the last position is length minus 1"],
        "explain": "Length 3 means positions 0, 1, 2.",
        "can_now": "You explained why indexing errors happen.",
    },
    {
        "id": "lists.fix", "concept": "lists", "kind": "fix", "role": "apply",
        "title": "Fix the last-item bug", "difficulty": 2, "minutes": 3,
        "hook": "last([\"a\", \"b\", \"c\"]) should return \"c\". Instead it crashes with IndexError.",
        "prompt": "Fix the function so it returns the last item of any non-empty list.",
        "code": "def last(items):\n    return items[len(items)]\n",
        "solution": "def last(items):\n    return items[len(items) - 1]\n",
        "tests": [
            {"fn": "last", "args": [["a", "b", "c"]], "expect": "c"},
            {"fn": "last", "args": [[7]], "expect": 7},
        ],
        "hints": [
            "If a list has 3 items, its positions are 0, 1, 2. What position is items[len(items)] asking for?",
            "The last position is len(items) - 1. (Python also allows items[-1] as a shortcut.)",
        ],
        "explain": "len(items) is 3, but the last position is 2. Subtracting one fixes it. Python also lets you write items[-1], which means 'one from the end' — a handy shortcut once you understand why the long form works.",
        "why": "You just fixed an indexing error by reasoning about positions, not by guessing. That is exactly what experienced programmers do.",
        "can_now": "You fixed an indexing error.",
    },
    {
        "id": "lists.build", "concept": "lists", "kind": "build", "role": "build",
        "title": "Build: shopping total", "difficulty": 2, "minutes": 4,
        "hook": "A list of prices, a loop, a running total. That's a real shopping-cart calculation.",
        "prompt": "Write total(prices) that adds up all the numbers in the list and returns the sum. Do it with a loop (not the built-in sum) so you see how it works.",
        "code": "def total(prices):\n    result = 0\n    return result\n",
        "solution": "def total(prices):\n    result = 0\n    for p in prices:\n        result = result + p\n    return result\n",
        "tests": [
            {"fn": "total", "args": [[3.5, 2.0, 4.5]], "expect": 10.0},
            {"fn": "total", "args": [[]], "expect": 0},
            {"fn": "total", "args": [[10]], "expect": 10},
        ],
        "hints": [
            "for p in prices: gives you each price in turn — no positions needed.",
            "Inside the loop: result = result + p.",
        ],
        "explain": "for p in prices walks the list item by item. This is the most common way to loop in Python — you rarely need positions. Adding each item to a running total is the accumulator pattern again.",
        "why": "You have now seen 'loop over items' and 'loop over positions'. Reach for items unless you truly need the position.",
        "can_now": "You built a list total with a loop.",
    },
    {
        "id": "lists.review1", "concept": "lists", "kind": "predict", "role": "review",
        "title": "Append and length", "difficulty": 2, "minutes": 2,
        "hook": "Lists grow.",
        "prompt": "What does this print?",
        "code": "nums = [10, 20]\nnums.append(30)\nprint(len(nums))\nprint(nums[1])",
        "answer": "3\n20",
        "hints": ["append adds to the end. Then count, then read position 1.", "After append: [10, 20, 30]. len is 3. nums[1] is 20."],
        "explain": "append adds one item to the end and the list gets longer. Position 1 is still the second item.",
        "can_now": "You can predict list changes after append.",
    },
    {
        "id": "lists.review2", "concept": "lists", "kind": "write", "role": "review",
        "title": "Count the big ones", "difficulty": 2, "minutes": 3,
        "hook": "Loop + decision + list.",
        "prompt": "Write count_over(nums, limit) that returns how many numbers in nums are greater than limit.",
        "code": "def count_over(nums, limit):\n    pass\n",
        "solution": "def count_over(nums, limit):\n    count = 0\n    for n in nums:\n        if n > limit:\n            count = count + 1\n    return count\n",
        "tests": [
            {"fn": "count_over", "args": [[1, 5, 9, 12], 5], "expect": 2},
            {"fn": "count_over", "args": [[], 3], "expect": 0},
        ],
        "hints": ["Start count at 0. Loop over items. If the item is over the limit, add 1.", "for n in nums: if n > limit: count = count + 1."],
        "explain": "Counting is accumulating by 1 only when a condition holds.",
        "can_now": "You wrote a filtered count over a list.",
    },
    {
        "id": "lists.cumulative", "concept": "lists", "kind": "write", "role": "cumulative",
        "title": "Challenge: biggest number", "difficulty": 3, "minutes": 5,
        "hook": "Find the maximum by hand. This is what max() does inside.",
        "prompt": "Write biggest(nums) that returns the largest number in a non-empty list, using a loop and an if (not the built-in max).",
        "code": "def biggest(nums):\n    pass\n",
        "solution": "def biggest(nums):\n    best = nums[0]\n    for n in nums:\n        if n > best:\n            best = n\n    return best\n",
        "tests": [
            {"fn": "biggest", "args": [[3, 9, 2]], "expect": 9},
            {"fn": "biggest", "args": [[-5, -1, -9]], "expect": -1},
            {"fn": "biggest", "args": [[4]], "expect": 4},
        ],
        "hints": ["Keep a 'best so far'. Start it as the first item, not 0 (what if all numbers are negative?).", "best = nums[0]; for n in nums: if n > best: best = n."],
        "explain": "The 'best so far' pattern: start with a real candidate, then let each item challenge it. Starting at 0 would fail for negative lists — a subtle, common bug.",
        "can_now": "You implemented max from scratch and avoided the negative-numbers trap.",
    },

    # ------------------------------------------------------------ while_loops
    {
        "id": "while_loops.hook", "concept": "while_loops", "kind": "predict", "role": "hook",
        "title": "Until it's done", "difficulty": 1, "minutes": 2,
        "hook": "A for loop knows how many times to run. A while loop doesn't — it keeps going until something changes.",
        "prompt": "What does this print?",
        "code": "n = 1\nwhile n < 20:\n    print(n)\n    n = n * 3",
        "answer": "1\n3\n9",
        "hints": [
            "Each turn: check n < 20; if true, print then triple. Stop when the check fails.",
            "1 → print, becomes 3. 3 → print, becomes 9. 9 → print, becomes 27. 27 < 20 is False, stop.",
        ],
        "explain": "while CONDITION: checks the condition, runs the block if it is True, then goes back and checks again. Something inside the block must change, or the loop never ends. Here n triples each time until it passes 20.",
        "explain_alt": "Like stirring until the sugar dissolves: you don't know how many stirs, you check after each one.",
        "why": "Games, menus and 'try again' prompts all use while — they run until the person does something.",
        "can_now": "You can trace a while loop and see why it stops.",
    },
    {
        "id": "while_loops.explain", "concept": "while_loops", "kind": "explain", "role": "apply",
        "title": "Infinite loop", "difficulty": 1, "minutes": 1,
        "hook": "Everyone writes one eventually. Knowing why makes it un-scary.",
        "prompt": "What happens if you delete the line n = n * 3, and why?",
        "model_answer": "n stays 1 forever, so n < 20 is always True and the loop never stops — an infinite loop printing 1 endlessly. Something inside the loop must move the condition toward False.",
        "checklist": ["Said the loop never stops", "Said why: the condition never becomes False"],
        "explain": "A while loop needs progress inside it.",
        "can_now": "You explained what makes a loop end.",
    },
    {
        "id": "while_loops.fix", "concept": "while_loops", "kind": "fix", "role": "apply",
        "title": "Fix the loop that never ends", "difficulty": 2, "minutes": 3,
        "hook": "halvings(100) should count how many times you can halve 100 before it drops below 1 (answer: 7). Right now it runs forever.",
        "prompt": "Fix the function so it stops and returns the count.",
        "code": "def halvings(x):\n    count = 0\n    while x >= 1:\n        count = count + 1\n    return count\n",
        "solution": "def halvings(x):\n    count = 0\n    while x >= 1:\n        x = x / 2\n        count = count + 1\n    return count\n",
        "tests": [
            {"fn": "halvings", "args": [100], "expect": 7},
            {"fn": "halvings", "args": [1], "expect": 1},
            {"fn": "halvings", "args": [0.5], "expect": 0},
        ],
        "hints": [
            "The condition is x >= 1. Does anything inside the loop change x?",
            "Add x = x / 2 inside the loop, so x shrinks each turn.",
        ],
        "explain": "The loop checks x, but nothing changed x, so the check was always True. Halving x inside the loop makes progress toward the exit.",
        "why": "When a loop hangs, ask one question: what inside the loop moves the condition toward False? If nothing does, that's the bug.",
        "can_now": "You fixed an infinite loop by adding progress.",
    },
    {
        "id": "while_loops.build", "concept": "while_loops", "kind": "build", "role": "build",
        "title": "Build: guess the number", "difficulty": 3, "minutes": 5,
        "hook": "A real game. It keeps asking until you get it.",
        "prompt": "The secret is 7. Read guesses with input() until the guess is 7. For a wrong guess print \"Too low\" or \"Too high\". When correct, print \"Got it!\" and stop.",
        "code": 'secret = 7\nguess = int(input())\nwhile guess != secret:\n    # print Too low / Too high, then read the next guess\n    guess = int(input())\nprint("Got it!")',
        "solution": 'secret = 7\nguess = int(input())\nwhile guess != secret:\n    if guess < secret:\n        print("Too low")\n    else:\n        print("Too high")\n    guess = int(input())\nprint("Got it!")',
        "io_tests": [
            {"stdin": "3\n9\n7\n", "expect": "Too low\nToo high\nGot it!"},
            {"stdin": "7\n", "expect": "Got it!"},
        ],
        "hints": [
            "Inside the loop: an if to decide low or high, then read the next guess (that's the progress).",
            "if guess < secret: print(\"Too low\") else: print(\"Too high\"), then guess = int(input()).",
        ],
        "explain": "while guess != secret keeps looping until the guess matches. Reading a new guess at the end of the block is what makes progress. int() converts the typed text to a number so < works.",
        "why": "This tiny game is the same loop as a login prompt, a menu, or a 'retry until the download works'.",
        "can_now": "You built a game with a while loop, a decision and input.",
    },
    {
        "id": "while_loops.review1", "concept": "while_loops", "kind": "predict", "role": "review",
        "title": "Count down", "difficulty": 2, "minutes": 2,
        "hook": "Trace it.",
        "prompt": "What does this print?",
        "code": 'n = 3\nwhile n > 0:\n    print(n)\n    n = n - 1\nprint("Go!")',
        "answer": "3\n2\n1\nGo!",
        "hints": ["Print, then subtract, until n is 0. Then the unindented line runs.", "3, 2, 1, then Go!"],
        "explain": "When the condition fails, execution continues after the loop.",
        "can_now": "You traced a countdown while loop.",
    },
    {
        "id": "while_loops.review2", "concept": "while_loops", "kind": "write", "role": "review",
        "title": "Digits", "difficulty": 3, "minutes": 4,
        "hook": "A trick with // and %: peel digits off a number.",
        "prompt": "Write digits(n) that returns how many digits a positive whole number has, using a while loop and // 10. digits(345) → 3.",
        "code": "def digits(n):\n    pass\n",
        "solution": "def digits(n):\n    count = 0\n    while n > 0:\n        n = n // 10\n        count = count + 1\n    return count\n",
        "tests": [
            {"fn": "digits", "args": [345], "expect": 3},
            {"fn": "digits", "args": [7], "expect": 1},
            {"fn": "digits", "args": [1000], "expect": 4},
        ],
        "hints": ["n // 10 removes the last digit. Count how many times until n hits 0.", "while n > 0: n = n // 10; count += 1."],
        "explain": "Each // 10 chops one digit off. Counting the chops counts the digits.",
        "can_now": "You used a while loop with integer division.",
    },

    # -------------------------------------------------------------- functions
    {
        "id": "functions.hook", "concept": "functions", "kind": "predict", "role": "hook",
        "title": "A recipe with a name", "difficulty": 1, "minutes": 2,
        "hook": "def lets you name a set of steps and run them whenever you like. Notice what prints, and in what order.",
        "prompt": "What does this print?",
        "code": 'def cheer(name):\n    return "Go " + name + "!"\n\nmessage = cheer("Ana")\nprint(message)\nprint(cheer("Kai"))',
        "answer": "Go Ana!\nGo Kai!",
        "hints": [
            "def only defines the recipe. Nothing runs until you call cheer(...).",
            "cheer(\"Ana\") returns the text Go Ana! which is stored and printed. Then cheer(\"Kai\") is printed directly.",
        ],
        "explain": "def cheer(name): defines a function called cheer that takes one input, name. The body runs only when you call it: cheer(\"Ana\"). return hands a value back to whoever called it. You can store that value (message = ...) or print it directly.",
        "explain_alt": "A function is a vending machine: put a coin in (the argument), get a snack out (the return value). Defining it is installing the machine; calling it is using it.",
        "why": "Functions let you write a thing once and use it a hundred times. They are also how you break a big problem into small named pieces.",
        "can_now": "You can read a function definition and its calls, and predict the order things happen.",
    },
    {
        "id": "functions.explain", "concept": "functions", "kind": "explain", "role": "apply",
        "title": "return vs print", "difficulty": 2, "minutes": 1,
        "hook": "The number-one function confusion, cleared up in one sentence.",
        "prompt": "What is the difference between  return x  and  print(x)  inside a function?",
        "model_answer": "print shows x on the screen and nothing else. return hands x back to the code that called the function, so it can be stored, compared or used in a calculation. A function that only prints gives back None.",
        "checklist": ["Said print shows on screen", "Said return gives the value back to the caller"],
        "explain": "print is for humans looking at the screen; return is for the rest of the program.",
        "can_now": "You explained return versus print.",
    },
    {
        "id": "functions.fix", "concept": "functions", "kind": "fix", "role": "apply",
        "title": "Fix the silent function", "difficulty": 2, "minutes": 3,
        "hook": "double(4) should give 8. It prints 8 but the test says it returned None. One word fixes it.",
        "prompt": "Fix double so it gives the value back to the caller.",
        "code": "def double(n):\n    print(n * 2)\n",
        "solution": "def double(n):\n    return n * 2\n",
        "tests": [
            {"fn": "double", "args": [4], "expect": 8},
            {"fn": "double", "args": [0], "expect": 0},
        ],
        "hints": [
            "Printing shows a value on screen; it does not hand it back. What keyword hands a value back?",
            "Replace print(n * 2) with return n * 2.",
        ],
        "explain": "A function without a return gives back None. The caller received None while the 8 went to the screen. return sends the value to the caller.",
        "why": "You have now seen the bug from both sides: the explanation, and the failing test. That pairing is how understanding sticks.",
        "can_now": "You fixed a function that printed instead of returning.",
    },
    {
        "id": "functions.build", "concept": "functions", "kind": "build", "role": "build",
        "title": "Build: a tiny toolkit", "difficulty": 2, "minutes": 5,
        "hook": "Two small helpers you will genuinely reuse.",
        "prompt": "Write two functions:\n  celsius(f) — converts Fahrenheit to Celsius: (f - 32) * 5 / 9\n  average(nums) — returns the mean of a non-empty list (use a loop for the sum).",
        "code": "def celsius(f):\n    pass\n\ndef average(nums):\n    pass\n",
        "solution": "def celsius(f):\n    return (f - 32) * 5 / 9\n\ndef average(nums):\n    total = 0\n    for n in nums:\n        total = total + n\n    return total / len(nums)\n",
        "tests": [
            {"fn": "celsius", "args": [212], "expect": 100.0},
            {"fn": "celsius", "args": [32], "expect": 0.0},
            {"fn": "average", "args": [[2, 4, 6]], "expect": 4.0},
            {"fn": "average", "args": [[5]], "expect": 5.0},
        ],
        "hints": [
            "Each function is a def with a return. average needs a loop to add, then divide by len(nums).",
            "return (f - 32) * 5 / 9  and  total / len(nums) after the loop.",
        ],
        "explain": "Two independent functions in one file. Each takes inputs, returns a result, and knows nothing about the other. That independence is what makes functions reusable.",
        "why": "Real programs are mostly collections of small functions like these, combined.",
        "can_now": "You built two reusable functions.",
    },
    {
        "id": "functions.review1", "concept": "functions", "kind": "predict", "role": "review",
        "title": "Two calls", "difficulty": 2, "minutes": 2,
        "hook": "Functions can call other functions.",
        "prompt": "What does this print?",
        "code": "def square(x):\n    return x * x\n\ndef sum_squares(a, b):\n    return square(a) + square(b)\n\nprint(sum_squares(3, 4))",
        "answer": "25",
        "hints": ["square(3) is 9, square(4) is 16.", "9 + 16 = 25."],
        "explain": "sum_squares uses square twice. Building on smaller functions is how big programs stay readable.",
        "can_now": "You traced nested function calls.",
    },
    {
        "id": "functions.review2", "concept": "functions", "kind": "write", "role": "review",
        "title": "Is it a vowel?", "difficulty": 2, "minutes": 3,
        "hook": "A function that returns True or False.",
        "prompt": "Write is_vowel(ch) that returns True if the single lowercase letter ch is a vowel (a, e, i, o, u), else False.",
        "code": "def is_vowel(ch):\n    pass\n",
        "solution": 'def is_vowel(ch):\n    return ch in "aeiou"\n',
        "tests": [
            {"fn": "is_vowel", "args": ["a"], "expect": True},
            {"fn": "is_vowel", "args": ["b"], "expect": False},
            {"fn": "is_vowel", "args": ["u"], "expect": True},
        ],
        "hints": ["ch in \"aeiou\" is already True or False. You can return it directly.", "return ch in \"aeiou\""],
        "explain": "A comparison produces True/False, so you can return it without an if. Functions that answer yes/no are called predicates.",
        "can_now": "You wrote a function that returns a boolean.",
    },
    {
        "id": "functions.cumulative", "concept": "functions", "kind": "write", "role": "cumulative",
        "title": "Challenge: count vowels", "difficulty": 3, "minutes": 5,
        "hook": "Loop over letters, decide, count, return.",
        "prompt": "Write count_vowels(text) that returns how many vowels (a, e, i, o, u, lowercase) are in text.",
        "code": "def count_vowels(text):\n    pass\n",
        "solution": 'def count_vowels(text):\n    count = 0\n    for ch in text:\n        if ch in "aeiou":\n            count = count + 1\n    return count\n',
        "tests": [
            {"fn": "count_vowels", "args": ["banana"], "expect": 3},
            {"fn": "count_vowels", "args": ["xyz"], "expect": 0},
            {"fn": "count_vowels", "args": [""], "expect": 0},
        ],
        "hints": ["for ch in text walks the letters one at a time, like a list.", "if ch in \"aeiou\": count = count + 1."],
        "explain": "A string behaves like a list of characters in a for loop. Count the ones that pass the test.",
        "can_now": "You combined a loop, a membership test and a counter inside a function.",
    },

    # ---------------------------------------------------------------- strings
    {
        "id": "strings.hook", "concept": "strings", "kind": "predict", "role": "hook",
        "title": "Slicing text", "difficulty": 2, "minutes": 2,
        "hook": "You can cut pieces out of text with the same [ ] you used on lists.",
        "prompt": "What does this print?",
        "code": 'word = "python"\nprint(word[0])\nprint(word[0:3])\nprint(word.upper())\nprint(len(word))',
        "answer": "p\npyt\nPYTHON\n6",
        "hints": [
            "word[0] is one character. word[0:3] is positions 0, 1, 2 (stops before 3). upper() shouts.",
            "p, pyt, PYTHON, 6.",
        ],
        "explain": "Text is a sequence of characters, so [position] and [start:stop] work like on lists — and stop is not included, just like range. .upper() returns a shouting copy; it does not change the original. len counts characters.",
        "why": "Slicing and methods are how programs clean up names, pull out file extensions and check passwords.",
        "can_now": "You can slice text and use a string method.",
    },
    {
        "id": "strings.explain", "concept": "strings", "kind": "explain", "role": "apply",
        "title": "Why stop is excluded", "difficulty": 2, "minutes": 1,
        "hook": "It's the same rule three times: range, list slices, string slices.",
        "prompt": "Why does \"python\"[0:3] give 3 characters, and how does that match range(0, 3)?",
        "model_answer": "The slice includes the start and stops before the stop, so 0:3 is positions 0, 1, 2 — three characters. range(0, 3) also gives 0, 1, 2. One rule: start included, stop excluded, and stop minus start is the count.",
        "checklist": ["Said the stop position is not included", "Connected it to range"],
        "explain": "Start included, stop excluded. Length = stop − start.",
        "can_now": "You explained the slicing rule.",
    },
    {
        "id": "strings.write", "concept": "strings", "kind": "write", "role": "apply",
        "title": "Initials", "difficulty": 2, "minutes": 3,
        "hook": "Turn \"ada lovelace\" into \"AL\".",
        "prompt": "Write initials(full_name) that returns the first letter of each word, upper-cased and joined. Use .split() to get the words.",
        "code": "def initials(full_name):\n    pass\n",
        "solution": 'def initials(full_name):\n    result = ""\n    for word in full_name.split():\n        result = result + word[0].upper()\n    return result\n',
        "tests": [
            {"fn": "initials", "args": ["ada lovelace"], "expect": "AL"},
            {"fn": "initials", "args": ["grace brewster murray hopper"], "expect": "GBMH"},
            {"fn": "initials", "args": ["tommy"], "expect": "T"},
        ],
        "hints": [
            ".split() turns \"ada lovelace\" into [\"ada\", \"lovelace\"]. Loop over that list.",
            "For each word, take word[0].upper() and add it to a result string.",
        ],
        "explain": "split() breaks text into a list of words on spaces. Then it is the accumulate pattern: start with \"\", add each initial.",
        "why": "split is the first step of almost every text-processing job: log lines, CSV rows, sentences.",
        "can_now": "You split text into words and processed each one.",
    },
    {
        "id": "strings.build", "concept": "strings", "kind": "build", "role": "build",
        "title": "Build: word counter", "difficulty": 2, "minutes": 3,
        "hook": "Every writing app has one. Yours is three lines.",
        "prompt": "Read one line of input and print how many words it has.",
        "code": "line = input()\n",
        "solution": "line = input()\nwords = line.split()\nprint(len(words))",
        "io_tests": [
            {"stdin": "the quick brown fox\n", "expect": "4"},
            {"stdin": "hello\n", "expect": "1"},
        ],
        "hints": ["split() gives a list of words; len() counts a list.", "print(len(line.split()))"],
        "explain": "split() → list of words → len() → count. Three tools chained.",
        "why": "Chaining small tools is the whole craft. You just did it.",
        "can_now": "You built a word counter.",
    },
    {
        "id": "strings.review1", "concept": "strings", "kind": "predict", "role": "review",
        "title": "Slice the end", "difficulty": 2, "minutes": 2,
        "hook": "Leaving out a number in a slice means 'to the end' or 'from the start'.",
        "prompt": "What does this print?",
        "code": 'name = "report.txt"\nprint(name[-3:])\nprint(name[:6])',
        "answer": "txt\nreport",
        "hints": ["[-3:] is the last three characters. [:6] is the first six.", "txt then report."],
        "explain": "Negative positions count from the end. An empty start means 0; an empty stop means the end.",
        "can_now": "You can slice from either end.",
    },
    {
        "id": "strings.review2", "concept": "strings", "kind": "write", "role": "review",
        "title": "Shout it", "difficulty": 1, "minutes": 2,
        "hook": "A variation.",
        "prompt": "Write shout(text) that returns the text in upper case followed by an exclamation mark.",
        "code": "def shout(text):\n    pass\n",
        "solution": 'def shout(text):\n    return text.upper() + "!"\n',
        "tests": [{"fn": "shout", "args": ["hi"], "expect": "HI!"}, {"fn": "shout", "args": [""], "expect": "!"}],
        "hints": [".upper() then add \"!\".", "return text.upper() + \"!\""],
        "explain": "Methods return new text you can keep building on.",
        "can_now": "You used a string method inside a function.",
    },

    # ------------------------------------------------------------------ dicts
    {
        "id": "dicts.hook", "concept": "dicts", "kind": "predict", "role": "hook",
        "title": "Look it up by name", "difficulty": 2, "minutes": 2,
        "hook": "Lists find things by position. Dictionaries find things by a key — like a phone book.",
        "prompt": "What does this print?",
        "code": 'ages = {"ana": 31, "kai": 27}\nprint(ages["kai"])\nages["lee"] = 40\nprint(len(ages))\nprint("ana" in ages)',
        "answer": "27\n3\nTrue",
        "hints": [
            "ages[\"kai\"] looks up the value stored under the key kai. Assigning to a new key adds an entry.",
            "27, then 3 entries, then True because ana is a key.",
        ],
        "explain": "A dictionary pairs keys with values: {\"kai\": 27}. Look up with d[key]. Add or change with d[key] = value. len counts pairs. key in d asks whether the key exists.",
        "explain_alt": "A contacts app: the name is the key, the number is the value. You never ask for 'contact number 3', you ask for 'Kai'.",
        "why": "Whenever you catch yourself wanting to look something up by name rather than position, that's a dictionary.",
        "can_now": "You can read, add to and check a dictionary.",
    },
    {
        "id": "dicts.explain", "concept": "dicts", "kind": "explain", "role": "apply",
        "title": "List or dictionary?", "difficulty": 2, "minutes": 1,
        "hook": "Choosing the right container is half of programming.",
        "prompt": "You are storing each student's score. Would you use a list or a dictionary, and why?",
        "model_answer": "A dictionary, with the student's name as the key and the score as the value, because you want to look up a score by name, not by position.",
        "checklist": ["Chose dictionary", "Gave the reason: look up by name/key"],
        "explain": "Position → list. Name → dictionary.",
        "can_now": "You explained when to use a dictionary.",
    },
    {
        "id": "dicts.fix", "concept": "dicts", "kind": "fix", "role": "apply",
        "title": "Fix the missing-key crash", "difficulty": 2, "minutes": 3,
        "hook": "lookup(book, \"zed\") crashes with KeyError when zed isn't in the book. It should return \"unknown\".",
        "prompt": "Fix the function so a missing name returns \"unknown\" instead of crashing.",
        "code": 'def lookup(book, name):\n    return book[name]\n',
        "solution": 'def lookup(book, name):\n    if name in book:\n        return book[name]\n    return "unknown"\n',
        "tests": [
            {"fn": "lookup", "args": [{"ana": "555"}, "ana"], "expect": "555"},
            {"fn": "lookup", "args": [{"ana": "555"}, "zed"], "expect": "unknown"},
        ],
        "hints": [
            "Check whether the key exists before using it: name in book.",
            "if name in book: return book[name] — otherwise return \"unknown\". (book.get(name, \"unknown\") is the one-line version.)",
        ],
        "explain": "d[key] crashes if the key is absent. Checking with in first avoids it. Python also offers d.get(key, default) which does the same in one call.",
        "why": "Handling the missing case is what separates a demo from a program people can rely on.",
        "can_now": "You handled a missing dictionary key.",
    },
    {
        "id": "dicts.build", "concept": "dicts", "kind": "build", "role": "build",
        "title": "Build: word frequency", "difficulty": 3, "minutes": 5,
        "hook": "How many times does each word appear? This is the core of search engines and spam filters.",
        "prompt": "Write freq(words) that takes a list of words and returns a dictionary of word → count. freq([\"a\", \"b\", \"a\"]) → {\"a\": 2, \"b\": 1}",
        "code": "def freq(words):\n    counts = {}\n    return counts\n",
        "solution": "def freq(words):\n    counts = {}\n    for w in words:\n        if w in counts:\n            counts[w] = counts[w] + 1\n        else:\n            counts[w] = 1\n    return counts\n",
        "tests": [
            {"fn": "freq", "args": [["a", "b", "a"]], "expect": {"a": 2, "b": 1}},
            {"fn": "freq", "args": [[]], "expect": {}},
        ],
        "hints": [
            "For each word: if it's already a key, add 1 to its value; otherwise set it to 1.",
            "if w in counts: counts[w] = counts[w] + 1 else: counts[w] = 1",
        ],
        "explain": "The counting-dictionary pattern: check if the key exists, then either increment or start at 1. You will write this dozens of times.",
        "why": "Counting occurrences is everywhere: votes, log errors, words, purchases.",
        "can_now": "You built a frequency counter with a dictionary.",
    },
    {
        "id": "dicts.review1", "concept": "dicts", "kind": "predict", "role": "review",
        "title": "Overwrite", "difficulty": 2, "minutes": 2,
        "hook": "Keys are unique.",
        "prompt": "What does this print?",
        "code": 'stock = {"apple": 3}\nstock["apple"] = 10\nstock["pear"] = 1\nprint(stock["apple"], len(stock))',
        "answer": "10 2",
        "hints": ["Assigning to an existing key replaces the value; it does not add a second apple.", "apple is 10; there are 2 keys."],
        "explain": "A key appears once. Assigning again overwrites.",
        "can_now": "You can predict dictionary updates.",
    },
    {
        "id": "dicts.review2", "concept": "dicts", "kind": "write", "role": "review",
        "title": "Total stock", "difficulty": 2, "minutes": 3,
        "hook": "Loop over a dictionary's values.",
        "prompt": "Write total_stock(stock) that returns the sum of all values in the dictionary. Use  for v in stock.values():",
        "code": "def total_stock(stock):\n    pass\n",
        "solution": "def total_stock(stock):\n    total = 0\n    for v in stock.values():\n        total = total + v\n    return total\n",
        "tests": [
            {"fn": "total_stock", "args": [{"apple": 3, "pear": 4}], "expect": 7},
            {"fn": "total_stock", "args": [{}], "expect": 0},
        ],
        "hints": [".values() gives just the numbers. Accumulate them.", "for v in stock.values(): total = total + v"],
        "explain": ".values() lets you loop over what's stored without caring about keys. .keys() and .items() are its siblings.",
        "can_now": "You summed a dictionary's values.",
    },
]
